---
- homebrew: name={{ item }} state=present
  with_items:
    - openssl
    - libyaml

# required for building Ruby <= 1.9.3-p0
- homebrew_tap: tap=homebrew/dupes state=present
  when: "{{ item.version | version_compare('1.9.3-p0', '<=') }}"
  with_items: "{{ rbenv.rubies }}"

- homebrew: name=apple-gcc42 state=present
  when: "{{ item.version | version_compare('1.9.3-p0', '<=') }}"
  with_items: "{{ rbenv.rubies }}"
