---
- name: include env vars
  include_vars: "{{ rbenv.env }}.yml"

- include: apt_build_depends.yml
  when: ansible_pkg_mgr == 'apt'
- include: yum_build_depends.yml
  when: ansible_pkg_mgr == 'yum'
- include: dnf_build_depends.yml
  when: ansible_pkg_mgr == 'dnf'
# - include: pacman_build_depends.yml # Arch Linux
#   when: ansible_pkg_mgr == 'pacman'
- include: homebrew_build_depends.yml
  when: ansible_os_family == 'Darwin'

- name: set rbenv_owner
  set_fact: 'rbenv_owner={{ rbenv_owner | default("root", true) }}'

- name: set tmp directory path
  set_fact: rbenv_tmpdir="{{ ansible_env.TMPDIR | default('/tmp') }}"
  when: rbenv_tmpdir is undefined

- include: system_install.yml
  when: rbenv.env == "system"
- include: user_install.yml
  when: rbenv.env != "system"
