---
- name: install apps
  hosts: all

  tasks:
  - name: update pacman.conf
    template: src=templates/pacman.conf dest=/etc/pacman.conf owner=root group=root mode=0644
    notify: update pacman caches
  - meta: flush_handlers

  - name: install common packages
    pacman: name={{ item }}
    with_items:
    - bind-tools
    - brasero
    - cups
    - gimp
    - handbrake
    - intltool
    - libdvdcss
    - libreoffice-fresh
    - mkvtoolnix-gui
    - mtpfs
    - mtr
    - nfs-utils
    - ogmrip
    - perl-image-exiftool
    - rawtherapee
    - simplescreenrecorder
    - transmission-gtk
    - vagrant
    - vlc
    - wireshark-cli
    - wireshark-gtk

  - name: import keys needed for AUR packages
    gpg_import: key_id="{{ item }}" servers=pgp.mit.edu
    with_items:
    - "1EB2638FF56C0C53" # cower, needed for pacaur
    become: yes
    become_user: ken

  - name: build common AUR packages
    packer: name={{ item }}
    with_items:
    - bluejeans
    #- dpkg
    - dropbox
    - ledger
    - packer-io
    - slack-desktop
    - spotify
    - thunar-dropbox

  - service: name=nfs-server enabled=yes

  handlers:
  - name: update pacman caches
    pacman: update_cache=yes
