---
- name: configure hardware
  hosts: all

  tasks:
    # configure the root mount
  - mount: name=/ src=/dev/mapper/vgcrypt-root fstype=ext4 opts="defaults,noatime,data=ordered" state=present
  - service: name=fstrim.timer enabled=yes state=started

    # configure swap
  - mount: name=none src=/dev/mapper/vgcrypt-swap fstype=swap state=present

    # Module configuration
  - template: src=templates/module_sound.conf dest=/etc/modprobe.d/snd_hda_intel.conf owner=root group=root mode=0644
  - template: src=templates/module_usb.conf dest=/etc/modprobe.d/usbcore.conf owner=root group=root mode=0644
  - template: src=templates/module_blacklist.conf dest=/etc/modprobe.d/blacklist.conf owner=root group=root mode=0644

    # Power management
  - pacman: name=tlp
  - template: src=templates/tlp.conf dest=/etc/default/tlp owner=root group=root mode=0644
  - service: name=tlp enabled=yes state=started

    # Plymouth for graphical boot
  - packer: name=plymouth
  - packer: name=plymouth-theme-dark-arch
  - pacman: name=ttf-dejavu # needed by plymouth
  - template: src=templates/plymouthd.conf dest=/etc/plymouth/plymouthd.conf owner=root group=root mode=0644

    # boot stuff
  - template: src=templates/vconsole.conf dest=/etc/vconsole.conf owner=root group=root mode=0644
  - template: src=templates/mkinitcpio.conf dest=/etc/mkinitcpio.conf owner=root group=root mode=0644
    notify:
    - build initramfs

    # allow non-root to access the KeepKey when plugged in
  - template: src=templates/keepkey-udev.rules dest=/etc/udev/rules.d/90-keepkey.rules owner=root group=root mode=0644

  handlers:
  - name: build initramfs
    shell: mkinitcpio -p linux
