---
- hosts: all
  vars:
    rbenv:
      env: user
      version: v1.1.0
      ruby_version: 2.3.4
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - ken
      rbenv_plugins:
      - name: "rbenv-vars"
        repo: "https://github.com/sstephenson/rbenv-vars.git"
        version: "master"
      - name: "ruby-build"
        repo: "https://github.com/sstephenson/ruby-build.git"
        version: "master"
      - name: "rbenv-default-gems"
        repo: "https://github.com/sstephenson/rbenv-default-gems.git"
        version: "master"
      - name: "rbenv-installer"
        repo: "https://github.com/fesplugas/rbenv-installer.git"
        version: "master"
      - name: "rbenv-update"
        repo: "https://github.com/rkh/rbenv-update.git"
        version: "master"
      - name: "rbenv-whatis"
        repo: "https://github.com/rkh/rbenv-whatis.git"
        version: "master"
      - name: "rbenv-use"
        repo: "https://github.com/rkh/rbenv-use.git"
        version: "master"
      - name: "rbenv-gemset"
        repo: "https://github.com/jf/rbenv-gemset.git"
        version: "master"
