---
- hosts: all
  vars:
    rbenv:
      env: user
      version: v1.1.1
      default_ruby: 2.4.3
      rubies:
        - version: 2.3.6
          env:
            PKG_CONFIG_PATH: /usr/lib/openssl-1.0/pkgconfig:/usr/lib/pkgconfig
        - version: 2.4.3
          env:
            PKG_CONFIG_PATH: /usr/lib/openssl-1.0/pkgconfig:/usr/lib/pkgconfig
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - ken
      rbenv_plugins:
      - name: "rbenv-vars"
        repo: "https://github.com/sstephenson/rbenv-vars.git"
        version: "master"
      - name: "ruby-build"
        repo: "https://github.com/sstephenson/ruby-build.git"
        version: "master"
      - name: "rbenv-default-gems"
        repo: "https://github.com/sstephenson/rbenv-default-gems.git"
        version: "master"
      - name: "rbenv-installer"
        repo: "https://github.com/rbenv/rbenv-installer.git"
        version: "master"
      - name: "rbenv-update"
        repo: "https://github.com/rkh/rbenv-update.git"
        version: "master"
      - name: "rbenv-whatis"
        repo: "https://github.com/rkh/rbenv-whatis.git"
        version: "master"
      - name: "rbenv-use"
        repo: "https://github.com/rkh/rbenv-use.git"
        version: "master"
      - name: "rbenv-gemset"
        repo: "https://github.com/jf/rbenv-gemset.git"
        version: "master"
