---
- hosts: all
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.2.3
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - ken
      rbenv_plugins:
      - name: "rbenv-vars"
        repo: "https://github.com/sstephenson/rbenv-vars.git"
        version: "v1.2.0"
      - name: "ruby-build"
        repo: "https://github.com/sstephenson/ruby-build.git"
        version: "v20151028"
      - name: "rbenv-default-gems"
        repo: "https://github.com/sstephenson/rbenv-default-gems.git"
        version: "v1.0.0"
      - name: "rbenv-installer"
        repo: "https://github.com/fesplugas/rbenv-installer.git"
        version: "8bb9d34d01f78bd22e461038e887d6171706e1ba"
      - name: "rbenv-update"
        repo: "https://github.com/rkh/rbenv-update.git"
        version: "32218db487dca7084f0e1954d613927a74bc6f2d"
      - name: "rbenv-whatis"
        repo: "https://github.com/rkh/rbenv-whatis.git"
        version: "v1.0.0"
      - name: "rbenv-use"
        repo: "https://github.com/rkh/rbenv-use.git"
        version: "v1.0.0"
      - name: "rbenv-gemset"
        repo: "https://github.com/jf/rbenv-gemset.git"
        version: "master"
